version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: servbatch-api
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=file:/app/data/servbatch.db
      - PROXY_API_KEY=${PROXY_API_KEY:-your-api-key}
      - JWT_SECRET=servbatch-api-jwt-secret-key
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - ADMIN_EMAIL=admin@example.com
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - ./prisma/migrations:/app/prisma/migrations
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000/api',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
